//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt3000.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTICIPOS
    {
        public long ID_ANTICIPOS { get; set; }
        public long ID_PACIENTE { get; set; }
        public string Detalle { get; set; }
        public decimal Valor { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
