//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt3000.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENCION
    {
        public ATENCION()
        {
            this.ADAPTACION_LENTES = new HashSet<ADAPTACION_LENTES>();
            this.CUENTA_PACIENTE = new HashSet<CUENTA_PACIENTE>();
            this.LENTE_DEFINITIVO = new HashSet<LENTE_DEFINITIVO>();
            this.LENTE_PRUEBA = new HashSet<LENTE_PRUEBA>();
            this.OFTALMOLOGIA = new HashSet<OFTALMOLOGIA>();
            this.RETINOSCOPIA_DILATADA = new HashSet<RETINOSCOPIA_DILATADA>();
            this.RX_EN_USO = new HashSet<RX_EN_USO>();
            this.RX_FINAL = new HashSet<RX_FINAL>();
            this.FACTURA = new HashSet<FACTURA>();
            this.LENTES_CONTACTO = new HashSet<LENTES_CONTACTO>();
        }
    
        public long ID_ATENCION { get; set; }
        public long ID_PACIENTE { get; set; }
        public string Tipo_Consulta { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public string Tipo_Seguro { get; set; }
        public string Observaciones { get; set; }
        public string DiagnosticoOD { get; set; }
        public string DiagnosticoOI { get; set; }
        public string Recomendaciones { get; set; }
        public int Usuario { get; set; }
        public bool Ate_Facturada { get; set; }
        public string OPTOMETRA { get; set; }
        public string Mpc { get; set; }
        public Nullable<bool> FACTURAR { get; set; }
        public string CUENTADIVIDIA { get; set; }
        public string DETALLEFACTURA { get; set; }
    
        public virtual ICollection<ADAPTACION_LENTES> ADAPTACION_LENTES { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual ICollection<CUENTA_PACIENTE> CUENTA_PACIENTE { get; set; }
        public virtual ICollection<LENTE_DEFINITIVO> LENTE_DEFINITIVO { get; set; }
        public virtual ICollection<LENTE_PRUEBA> LENTE_PRUEBA { get; set; }
        public virtual ICollection<OFTALMOLOGIA> OFTALMOLOGIA { get; set; }
        public virtual ICollection<RETINOSCOPIA_DILATADA> RETINOSCOPIA_DILATADA { get; set; }
        public virtual ICollection<RX_EN_USO> RX_EN_USO { get; set; }
        public virtual ICollection<RX_FINAL> RX_FINAL { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual ICollection<LENTES_CONTACTO> LENTES_CONTACTO { get; set; }
    }
}
