//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt3000.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTORIO
    {
        public CONSULTORIO()
        {
            this.HONRARIOATENCION = new HashSet<HONRARIOATENCION>();
        }
    
        public short ID_CONSULTORIO { get; set; }
        public string Nombre { get; set; }
        public string Detalle { get; set; }
        public short ID_SUCURSAL { get; set; }
    
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual ICollection<HONRARIOATENCION> HONRARIOATENCION { get; set; }
    }
}
