//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt3000.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA_PACIENTE
    {
        public CUENTA_PACIENTE()
        {
            this.DETALLE = new HashSet<DETALLE>();
        }
    
        public long ID_CUENTA_PACIENTE { get; set; }
        public long ID_CLIENTE { get; set; }
        public long ID_ATENCION { get; set; }
        public long AGRUPACION { get; set; }
    
        public virtual ATENCION ATENCION { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DETALLE> DETALLE { get; set; }
    }
}
