//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt3000.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public FACTURA()
        {
            this.FACTURA_PAGO = new HashSet<FACTURA_PAGO>();
        }
    
        public long ID_FACTURA { get; set; }
        public long ID_ATENCION { get; set; }
        public System.DateTime Fecha_Emision { get; set; }
        public bool Arqueada { get; set; }
        public Nullable<System.DateTime> Fecha_Arqueo { get; set; }
        public short ID_CAJA { get; set; }
        public string Numero_Factura { get; set; }
    
        public virtual ATENCION ATENCION { get; set; }
        public virtual CAJA CAJA { get; set; }
        public virtual ICollection<FACTURA_PAGO> FACTURA_PAGO { get; set; }
    }
}
