//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt3000.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA_PAGO
    {
        public FORMA_PAGO()
        {
            this.FACTURA_PAGO = new HashSet<FACTURA_PAGO>();
        }
    
        public int ID_FORMAPAGO { get; set; }
        public string Detalle { get; set; }
        public bool Estado { get; set; }
        public short CodigoSri { get; set; }
        public bool Diferido { get; set; }
    
        public virtual ICollection<FACTURA_PAGO> FACTURA_PAGO { get; set; }
    }
}
