//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt3000.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_MEDIDAS
    {
        public long HC { get; set; }
        public long Atencion { get; set; }
        public string Paciente { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TipoAtencion { get; set; }
        public string MPC { get; set; }
        public string Esfera { get; set; }
        public string Cilindro { get; set; }
        public string Eje { get; set; }
        public string A_D_D { get; set; }
        public string AVL { get; set; }
        public string AVC { get; set; }
        public string ALT { get; set; }
        public string DNP_DP { get; set; }
        public string OJO { get; set; }
        public string DiagnosticoOD { get; set; }
        public string DiagnosticoOI { get; set; }
        public string Observaciones { get; set; }
        public string R_Esfera { get; set; }
        public string R_Cilindro { get; set; }
        public string R_Eje { get; set; }
        public string R_Avl { get; set; }
        public string EsferaDer { get; set; }
        public string CilindroDer { get; set; }
        public string EjeDer { get; set; }
        public string TipoDer { get; set; }
        public string EsferaIz { get; set; }
        public string CilindroIz { get; set; }
        public string EjeIz { get; set; }
        public string TipoIz { get; set; }
    }
}
