//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt3000.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        public MEDICO()
        {
            this.HONRARIOATENCION = new HashSet<HONRARIOATENCION>();
        }
    
        public int ID_MEDICO { get; set; }
        public int ID_USUARIO { get; set; }
        public string Identificacion { get; set; }
        public string Especialidad { get; set; }
        public string Email { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public short TiempoConsulta { get; set; }
    
        public virtual ICollection<HONRARIOATENCION> HONRARIOATENCION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
