//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt3000.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden1
    {
        public long ID_ORDEN1 { get; set; }
        public Nullable<long> AteCodigo { get; set; }
        public Nullable<long> CodPaciente { get; set; }
        public System.DateTime FechaPedido { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public string EsferaDer { get; set; }
        public string EsferaIz { get; set; }
        public string CilindroDer { get; set; }
        public string CilindroIz { get; set; }
        public string EjeDer { get; set; }
        public string EjeIz { get; set; }
        public string AddDer { get; set; }
        public string AddIz { get; set; }
        public string AltDer { get; set; }
        public string AltIz { get; set; }
        public string DnpDer { get; set; }
        public string DnpIz { get; set; }
        public string Mecanica { get; set; }
        public string Mayor { get; set; }
        public string Horinzotal { get; set; }
        public string Verical { get; set; }
        public string Puente { get; set; }
        public string CodArmazon { get; set; }
        public string Material { get; set; }
        public string Filtros { get; set; }
        public string Tinturado { get; set; }
        public string Luna { get; set; }
        public string Bisel { get; set; }
        public string Observaciones { get; set; }
        public int ID_Usuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<bool> GENERADO { get; set; }
        public Nullable<bool> enviado { get; set; }
        public Nullable<bool> RECIBIDO { get; set; }
        public Nullable<bool> ENTREGADO { get; set; }
    }
}
