//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt3000.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        public PACIENTE()
        {
            this.AGENDA = new HashSet<AGENDA>();
            this.ATENCION = new HashSet<ATENCION>();
            this.ANTICIPOS = new HashSet<ANTICIPOS>();
        }
    
        public long ID_PACIENTE { get; set; }
        public short ID_TIPO { get; set; }
        public string Identificacion { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Direccion { get; set; }
        public string Celular { get; set; }
        public string Convencional { get; set; }
        public string Email { get; set; }
        public System.DateTime F_Nacimiento { get; set; }
        public string Ocupacion { get; set; }
        public int Usuario { get; set; }
    
        public virtual ICollection<AGENDA> AGENDA { get; set; }
        public virtual ICollection<ATENCION> ATENCION { get; set; }
        public virtual CONVENIO CONVENIO { get; set; }
        public virtual ICollection<ANTICIPOS> ANTICIPOS { get; set; }
    }
}
