//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt3000.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETINOSCOPIA_DILATADA
    {
        public long ID_RETINOSCOPIA { get; set; }
        public long ID_ATENCION { get; set; }
        public string Esfera { get; set; }
        public string Cilindro { get; set; }
        public string Eje { get; set; }
        public string Avl { get; set; }
        public string OJO { get; set; }
    
        public virtual ATENCION ATENCION { get; set; }
    }
}
